### ISSUE TITLE
[TVD]: Plasma crashes when closing certain apps while the script is enabled

### ISSUE THREAD

**Issue by SamuXzX** [Ubiquitine/kwin-scripts#6] opened 2024-05-09 12:55 UTC
For some time I noticed that closing some applications, like Google Chrome (Flatpak), [teams-for-linux](https://github.com/IsmaelMartinez/teams-for-linux), Minecraft and some minor things, it seems that Plasma or Kwin crash, making other applications (for example Firefox or Whatsie) crash too. Other applications simply don't crash.

I tried making a screencast, but the issue messes with Spectacle, so even if the recording keeps going, it freeze when I stop the recording.

There's no problem if I disable Temporary Virtual Desktops.

**Comment by Ubiquitine** [comment] 2024-05-11 06:47
Closing this one as a duplicate of [this issues](https://github.com/Ubiquitine/kwin-scripts/issues/3). 
Although you did provide a bit more useful information here.

**Closed as not planned by Ubiquitine** 2024-05-11 06:47 UTC
Labels: duplicate, TVD
